In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
dframe= DataFrame(np.arange(4*4).reshape(4,4))

In [5]:
blender= np.random.permutation(4) # create a random permutation of 0:3
blender

array([2, 0, 1, 3])

In [6]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
dframe.take(blender)  # axis=0 by default

0   1   2   3
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [8]:
box= np.array([1,2,3])

In [10]:
shaker= np.random.randint(low=0,high=len(box),size=10) # creates random integers. note that high=3 isn't included [0,1,2,3)
shaker

array([1, 2, 1, 0, 0, 1, 2, 2, 2, 2])

In [11]:
hand_grabs=box.take(shaker)   # grab the value from the indeces of shaker (shaker's indeces ->box's value)
hand_grabs

array([2, 3, 2, 1, 1, 2, 3, 3, 3, 3])