In [1]:
import numpy as np

In [2]:
arr= np.arange(0,11); arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]=100; arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr=np.arange(0,11)

In [8]:
sub_arr= arr[0:6]
sub_arr[:]=99
arr  # If you take a slice of array and change it, that affects an original one to avoid memory problem

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
arr_copy=arr.copy()

In [33]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [13]:
arr_2d[1]  # returns the SECOND row

array([20, 25, 30])

In [14]:
arr_2d[1][0] # second row, first column

20

In [15]:
arr_2d[1,0]  # same return as above

20

In [16]:
arr_2d[:2,1:] # till second row. "stop" is not included

array([[10, 15],
       [25, 30]])

In [35]:
arr2d= np.zeros((10,10))

In [24]:
arr_length=arr2d.shape[1]  # "shape" returns a combination of nr of rows and columns. [1] takes the nr of colums [length]
arr_length

10

In [36]:
for i in range(arr_length):
    arr2d[i] = i
arr2d 

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [38]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [41]:
arr2d[[3,7,5,1]]

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])