In [1]:
import numpy as np

In [3]:
arr =np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load("myarray.npy")  # .npy as extension 

array([0, 1, 2, 3, 4])

In [7]:
arr1=np.load("myarray.npy")
arr2 = arr

In [9]:
np.savez("ziparray.npz",x=arr1,y=arr2)  # save multiple arrays as zip file (.npz) : you can omit extension
archive_array = np.load("ziparray.npz")

In [10]:
archive_array["x"]

array([0, 1, 2, 3, 4])

In [11]:
archive_array["y"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.savetxt("mytextarray.txt",arr,delimiter=",")  #delimiter: what saparates each value

In [17]:
arr = np.loadtxt("mytextarray.txt", delimiter=",")
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])