In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A= np.random.randn(10) ;A # 10 obseravatioins randomly selected from standard normal distribution

array([ 1.22295686, -0.25623631,  0.00917597, -0.25396796,  0.03230231,
        0.21332948,  1.16459075,  0.83986356, -0.5515145 ,  1.21454864])

In [9]:
B= np.random.randn(10); B

array([ 0.03654993,  0.46947777, -1.19044351,  0.96819159, -0.35389626,
        0.88286371, -1.4121352 , -1.47466068, -0.1739129 ,  3.10973494])

In [10]:
# binary functions
np.add(A,B)  # A+B

array([ 1.25950679,  0.21324145, -1.18126753,  0.71422363, -0.32159395,
        1.09619319, -0.24754445, -0.63479712, -0.7254274 ,  4.32428358])

In [11]:
np.maximum(A,B)  # compare A and B, and select the bigger

array([ 1.22295686,  0.46947777,  0.00917597,  0.96819159,  0.03230231,
        0.88286371,  1.16459075,  0.83986356, -0.1739129 ,  3.10973494])

In [12]:
website="http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)   # You can check all the available math operations (universal functions)

True