In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]
my_list2=[11,22,33,44]
my_lists=[my_list1,my_list2]

In [4]:
my_array1=np.array(my_list1)
my_array2=np.array(my_lists);my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [7]:
my_array2.shape # ask the shape of array

(2, 4)

In [8]:
my_array2.dtype #find out the data type of array

dtype('int64')

In [13]:
my_zeros_array=np.zeros(5); my_zeros_array  # martix with zeros. Default nr of rows: 1

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
my_zeros_array.dtype# returns values w/ decimal points -> floating 

dtype('float64')

In [15]:
np.ones([5,5]) #  matrix filled with one

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.empty(5) # matrix w/o initial entries

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
np.eye(5) # identical matrix

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(5) # evenly  spaced values within a given interval. default start=0, step=1

array([0, 1, 2, 3, 4])

In [26]:
np.arange(start=5, stop=50, step=2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])